---
title: "KRAS_DMS_figure_1"
output: html_document
date: "2025-07-10"
---

```{r setup}

library(tidyverse)
library(magrittr)
library(data.table)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(ggrepel)
library(janitor)
library(ggpubr)

options(datatable.fread.datatable=FALSE)

```

# --- Figure 1A: HA1E KRAS WT DMS screen heatmap --- #

```{r}

set.seed(1234)

metadata <- fread("./datasets_publication/figure_1/kras_structure_annotation.csv") %>%
  dplyr::arrange(pos)

aa_properties <- data.frame(group = c("Small hydrophobic", "Small hydrophobic", "Small hydrophobic", "Small hydrophobic", "Small hydrophobic", "Special Cases", "Special Cases", "Special Cases", "Polar Uncharged", "Polar Uncharged", "Polar Uncharged", "Polar Uncharged", "Positive", "Positive", "Positive", "Negative", "Negative", "Large Hydrophobic", "Large Hydrophobic", "Large Hydrophobic"),
                            aa = c("A", "I", "L", "M", "V", "C", "G", "P", "S", "T", "N", "Q", "K", "R", "H", "D", "E", "F", "W", "Y"))

rownames(aa_properties) <- aa_properties$aa

data <- readxl::read_excel("./datasets_publication/figure_1/Extended Data Table 1 UPDATED.xlsx", sheet = 2) %>%
  janitor::clean_names() %>%
  dplyr::mutate(wt_aa = paste(wt_aa, pos, sep = "")) %>%
  dplyr::select(wt_aa, mut_aa, ha1e_wt_lfc) %>%
  tidyr::pivot_wider(names_from = "wt_aa", values_from = "ha1e_wt_lfc") %>%
  tibble::column_to_rownames("mut_aa") %>%
  .[aa_properties$aa, metadata$wt_aa]

metadata$average <- apply(data, 2, function(x) mean(x, na.rm = T))
  
min <- -2
mid <- 0
max <- 2.5
a <- min + round(((mid-min) / 3), digits = 1)
b <- mid - round(((mid-min) / 3), digits = 1)

c <- mid + (round(((max-mid) / 3), digits = 1))
d <- max - round(((max-mid) / 3), digits = 1)

col_fun = colorRamp2(c(min, a, b, mid, c, d, max), c("#3B81C4","#81C2E7", "#DAF2F8", "#FFFFFF","#FF9286", "#EB001C", "#940017"))

top_annotation = HeatmapAnnotation(domain_1 = metadata$domain1, 
                                   domain_2 = metadata$domain2,
                                   domain_3 = metadata$domain3,
                                   average = anno_lines(metadata$average, height = unit(1, "cm")),
                                   annotation_label = gt_render(c("**Lobe**",
                                                                  "**Secondary structure**",
                                                                  "**Functionnal motif**",
                                                                  "**Average**"),
                                                                gp = gpar(fontsize = 4)),
                                   col = list(domain_1 = c("Effector lobe" = "#d46917",
                                                             "Allosteric lobe" = "#18a2d9",
                                                             "HVR" = "#ccbb39"),
                                              domain_2 = c("B1" = "#bdbdbd", 
                                                           "B2" = "#bdbdbd", 
                                                           "B3" = "#bdbdbd", 
                                                           "B4" = "#bdbdbd", 
                                                           "B5" = "#bdbdbd",
                                                           "B6" = "#bdbdbd", 
                                                           "a1" = "#666666",
                                                           "a2" = "#666666",
                                                           "a3" = "#666666",
                                                           "a4" = "#666666",
                                                           "a5" = "#666666"),
                                              domain_3 = c("G1/p-loop" = "red",
                                                           "G2/Switch 1" = "blue",
                                                           "G3/Switch 2" = "forestgreen",
                                                           "G4" = "#916c46",
                                                           "G5" = "black", 
                                                           "CAAX" = "#ff8000")),
                                   show_legend = c(TRUE, TRUE, TRUE, FALSE),
                                   na_col = "white",
                                   border = TRUE,
                                   simple_anno_size = unit(2, "mm"),
                                   show_annotation_name = c(TRUE, TRUE, TRUE, TRUE),
                                   annotation_name_side = "left")
  
left_annotation = HeatmapAnnotation(properties = aa_properties$group,
                                    annotation_label = gt_render(c("**properties**"),
                                                                 gp = gpar(fontsize = 4)),
                                    col = list(properties = c("Small hydrophobic" = "#D3BC25",
                                                              "Special Cases" = "#54C8B8",
                                                              "Polar Uncharged" = "#EAAE46",
                                                              "Positive" = "#F48CBA", 
                                                              "Negative" = "#87C74A",
                                                              "Large Hydrophobic" = "#F89E95",
                                                              "STOP" = "grey30")),
                                    show_legend = c(TRUE),
                                    na_col = "black",
                                    which = "row",
                                    border = TRUE,
                                    simple_anno_size = unit(2, "mm"),
                                    show_annotation_name = TRUE,
                                    annotation_name_side = "bottom")

labels <- c(12,13,14,19,23,34,59,61,68,83,116,117,145,146,181,185)
position_labels <- columnAnnotation(foo = anno_mark(at = labels - 1, # -1 to adjust for the removal of M1
                                                    labels = metadata[metadata$pos %in% labels, "wt_aa"],
                                                    labels_rot = 90,
                                                    link_width = unit(7.5, "mm"),
                                                    which = "column",
                                                    side = "bottom",
                                                    labels_gp = gpar(fontsize = 7.5)))

data <- data[aa_properties$aa,]

draw(Heatmap(as.matrix(data), 
             col = col_fun,
             heatmap_legend_param = list(title = "LFC", at = c(min, 0, max), border = "black"), # activating potential
             row_names_gp = gpar(fontsize = 5),
             column_names_gp = gpar(fontsize = 3.3),
             top_annotation = top_annotation,
             bottom_annotation = position_labels,
             left_annotation = left_annotation,
             cluster_rows = F,
             cluster_columns = F,
             column_km = NULL,
             row_gap = unit(0.75, "mm"),
             na_col = "grey50",
             show_row_names = TRUE,
             show_column_names = FALSE,
             row_names_side = "left",
             row_dend_reorder = TRUE,
             column_dend_reorder = TRUE,
             show_row_dend = TRUE,
             width = unit(15, "cm"),
             height = unit(5, "cm"),
             border_gp = gpar(col = "black", lty = 1),
             rect_gp = gpar(col = "white", lwd = 0.05)))

```

# --- Figure 1B: HA1E KRAS WT DMS screen / stats to map onto crystal structure --- #

```{r}

data <- readxl::read_excel("./datasets_publication/figure_1/Extended Data Table 1 UPDATED.xlsx", sheet = 2) %>%
  janitor::clean_names() %>%
  dplyr::mutate(wt_aa = paste(wt_aa, pos, sep = "")) %>%
  dplyr::select(wt_aa, mut_aa, ha1e_wt_lfc)

cutoff <- mean(data$ha1e_wt_lfc, na.rm = TRUE) + 2*sd(data$ha1e_wt_lfc, na.rm = TRUE)

stats_to_map <- data %>%
  dplyr::group_by(wt_aa) %>%
  dplyr::summarise(mean = mean(ha1e_wt_lfc, na.rm = T),
                   max = max(ha1e_wt_lfc, na.rm = T),
                   min = min(ha1e_wt_lfc, na.rm = T),
                   n_above_cutoff = sum(ha1e_wt_lfc >= cutoff, na.rm = TRUE))

# the rest of the mapping is done using UCSF chimera with the define/render by attribute embedded functions. The color of the residue being proportional to the max LFC at that residue and the worm size to the number of mutation at that residue scoring > that the transforming cutoff (~0.68)

```

# --- Figure 1C: HA1E KRAS WT DMS screen / Activating potential vs COSMIC incidences --- #

```{r}

set.seed(1234)

data <- readxl::read_excel("./datasets_publication/figure_1/Extended Data Table 1 UPDATED.xlsx", sheet = 2) %>%
  janitor::clean_names() %>%
  dplyr::mutate(wt_aa = paste(wt_aa, pos, sep = ""),
                mutation = paste(wt_aa, mut_aa, sep = "")) %>%
  dplyr::select(mutation, ha1e_wt_lfc)

nucleotide_changes <- fread("./datasets_publication/figure_1/kras_wt_nucleotide_changes.csv") %>%
  dplyr::mutate(min_nt_change = case_when(n_SNS != 0 ~ "SNS",
                                          n_SNS == 0 & n_DNS != 0 ~ "DNS",
                                          n_SNS == 0 & n_DNS == 0 & n_TNS != 0 ~ "TNS")) %>%
  dplyr::select(mutation, min_nt_change)

# import KRAS variant annotation queried from oncoKB via cBioportal #

oncokb_annotation <- fread("./datasets_publication/figure_1/oncoKB_annotation_022123.csv") %>%
  janitor::clean_names() %>%
  dplyr::rename(annotation = oncogenic) %>%
  dplyr::filter(!annotation %in% c("Resistance"))

# --- get incidence for KRAS variants in COSMIC v101 (this section has been updated to pull from the v101 and no longer from the v97 release) --- #

cosmic_v101_phenotype_id <- fread("./datasets_publication/figure_1/Cosmic_Classification_v101_GRCh38.tsv") %>% 
  janitor::clean_names() %>%
  dplyr::filter(primary_site %in% c("lung", "pancreas", "large_intestine"),
                primary_histology == "carcinoma") %>%
  dplyr::filter(
    (primary_site == "pancreas" & 
       !site_subtype_1 %in% c("ampulla_of_Vater", "extrapancreatic") & 
       primary_histology == "carcinoma" & 
       histology_subtype_1 %in% c("ductal_carcinoma", "adenocarcinoma")) |
      
    (primary_site == "lung" & 
       primary_histology == "carcinoma" &
       histology_subtype_1 %in% c("non_small_cell_carcinoma", "adenocarcinoma")) |
      
    (primary_site == "large_intestine" &
       site_subtype_1 %in% c("colon", "rectum") & 
       histology_subtype_1 %in% c("adenocarcinoma"))
    )

metadata_cosmic_v101 <- fread("./datasets_publication/figure_1/Cosmic_Sample_v101_GRCh38.tsv", data.table = FALSE) %>% 
  janitor::clean_names() #%>% dplyr::filter(cosmic_phenotype_id %in% cosmic_v101_phenotype_id$cosmic_phenotype_id) # uncomment to filter only specific tissue types

counts <- fread("./datasets_publication/figure_1/Cosmic_MutantCensus_Tsv_v101_GRCh38.tsv") %>% 
  janitor::clean_names() %>%
  dplyr::filter(cosmic_sample_id %in% metadata_cosmic_v101$cosmic_sample_id) %>%
  dplyr::mutate(mutation_aa = gsub("p.", "", mutation_aa),
                mutation_aa = str_remove_all(mutation_aa, " ")) %>%
  dplyr::filter(!grepl("_|del|ins|dup|fs", mutation_aa),
                !str_detect(mutation_aa, fixed("*")),
                !mutation_aa == "?",
                mutation_description == "missense_variant"
                ) %>%
  dplyr::group_by(mutation_aa) %>%
  dplyr::summarise(cosmic_count = n()) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(cosmic_incidence = log10(cosmic_count + 1)) %>%
  dplyr::rename(mutation = mutation_aa)


data %<>%
  dplyr::left_join(counts, by = "mutation") %>%
  dplyr::left_join(oncokb_annotation %>% dplyr::select(mutation, annotation), by = "mutation") %>%
  dplyr::left_join(nucleotide_changes, by = "mutation") %>%
  dplyr::mutate(cosmic_count = ifelse(is.na(cosmic_count), 0, cosmic_count),
                cosmic_incidence = ifelse(is.na(cosmic_incidence), 0, cosmic_incidence),
                annotation = ifelse(is.na(annotation), "Unknown", annotation),
                annotation = factor(annotation, levels = rev(c("Unknown", "Inconclusive", "Likely Neutral", "Likely Oncogenic", "Oncogenic"))),
                min_nt_change = factor(min_nt_change, levels = c("SNS", "DNS", "TNS"))) %>%
  dplyr::arrange(annotation)

cutoff <- mean(data$ha1e_wt_lfc, na.rm = TRUE) + 2*sd(data$ha1e_wt_lfc, na.rm = TRUE)


label <- data %>%
  dplyr::filter(annotation == "Oncogenic" |
                  (annotation == "Likely Oncogenic" & ha1e_wt_lfc > 0 & cosmic_incidence > 0) |
                  (min_nt_change == "DNS" & ha1e_wt_lfc > 2) |
                  (min_nt_change == "TNS" & ha1e_wt_lfc > quantile(ha1e_wt_lfc, 0.99, na.rm = TRUE))) %>%
  dplyr::distinct(mutation, .keep_all = TRUE)


data %>%
  ggplot(aes(x = ha1e_wt_lfc, y = cosmic_incidence)) +
  geom_point(aes(size = annotation, color = min_nt_change), shape = 16) +
  theme_test() +
  theme(aspect.ratio = 1,
        axis.ticks = element_line(colour = "black", size = 0.5),
        axis.text.x = element_text(angle = 0, color = "black", size = 10),
        axis.text.y = element_text(angle = 0, color = "black", size = 10)) +
  scale_color_manual(values = c("SNS" = "red", "DNS" = "navy", "TNS" = "#00630c"), , name = "Minimum nucleotide \nchange:") +
  scale_size_manual(breaks = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    labels = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    values = c(0.75, 0.75, 1.5, 2.5, 4),
                    name = "OncoKB annotation:") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  geom_vline(xintercept = cutoff, size = 0.25, linetype = "dashed", color = "#d6d6d6") +
  geom_vline(xintercept = 0, size = 0.25, linetype = "dashed", color = "grey50") +
  ggpubr::stat_cor(aes(color = min_nt_change, label = paste(..r.label.., ..p.label.., sep = "~`,`~")), label.x.npc = "left", label.y.npc = "top" , size = 2) +
  xlab("Transforming potential") +
  ylab("Cosmic incidence (Log10 count+1)") +
  geom_text_repel(data = .%>% dplyr::filter(mutation %in% label$mutation), 
                  aes(label = mutation, color = min_nt_change), size = 1.75, force = 35, min.segment.length = 0.1, segment.size = 0.15) 
    

plot1 <- data %>%
  ggplot(aes(x = ha1e_wt_lfc, y = cosmic_incidence)) +
      geom_vline(xintercept = 0, size = 0.2, linetype = "solid", color = "black") +
  geom_hline(yintercept = 0, size = 0.2, linetype = "solid", color = "black") +
  geom_point(aes(size = annotation, color = min_nt_change), shape = 16) +
      geom_point(aes(size = annotation, color = min_nt_change), shape = 21,, color= "black") +
  theme(aspect.ratio = 1,
        axis.ticks = element_line(colour = "black", size = 7),
        axis.text.x = element_text(angle = 0, color = "black", size = 14),
        axis.text.y = element_text(angle = 0, color = "black", size = 14)) +
  scale_color_manual(values = c("SNS" = "red", "DNS" = "navy", "TNS" = "#00630c"), , name = " nucleotide \nchange:") +
  scale_size_manual(breaks = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    labels = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    values = c(0.75, 0.75, 1.5, 2.5, 4),
                    name = "OncoKB annotation:") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  geom_vline(xintercept = cutoff, size = 0.25, linetype = "dashed", color = "#d6d6d6") +
  ggpubr::stat_cor(aes(color = min_nt_change, label = paste(..r.label.., ..p.label.., sep = "~`,`~")), label.x.npc = "left", label.y.npc = "top" , size = 4) +
   geom_smooth(aes(color = min_nt_change), size = 0.5, method = "lm", se = FALSE) +
  xlab("Transforming potential") +
  ylab("Cosmic incidence (Log10 count+1)") +
  geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% label$mutation) %>% 
                    filter(ha1e_wt_lfc > 1 | cosmic_incidence > 1.6) %>% 
                    dplyr::filter(!mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation, color = min_nt_change), size = 4, force = 35, min.segment.length = 0.05, segment.size = 0.1) +
    geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation, color = min_nt_change), size = 4, nudge_x = 0.2, nudge_y = 0.1, min.segment.length = 0.2, segment.size = 0.2) +
  theme_classic() +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_y_continuous(limits = c(-0.5, 4.5), breaks = seq(-2, 4, by = 1))
    

plot2 <- data %>%
  ggplot(aes(x = ha1e_wt_lfc, y = cosmic_incidence)) +
   geom_smooth(aes(color = min_nt_change),color = "white", size = 0.5, method = "lm", se = FALSE) +
     geom_smooth(aes(), color = "black", size = 0.5, method = "lm", se = FALSE) +
      geom_hline(yintercept = 0, size = 0.2, linetype = "solid", color = "black") +
      geom_vline(xintercept = 0, size = 0.2, linetype = "solid", color = "black") +
  geom_point(aes(size = annotation), shape = 16,  alpha = 0.3) +
      geom_point(aes(size = annotation, color = min_nt_change), shape = 21,, color= "black") +
  theme(aspect.ratio = 1,
        axis.ticks = element_line(colour = "black", size = 7),
        axis.text.x = element_text(angle = 0, color = "black", size = 14),
        axis.text.y = element_text(angle = 0, color = "black", size = 14)) +
 # scale_color_manual(values = c("SNS" = "red", "DNS" = "navy", "TNS" = "#00630c"), , name = "Minimum nucleotide \nchange:") +
  scale_size_manual(breaks = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    labels = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    values = c(0.75, 0.75, 1.5, 2.5, 4),
                    name = "OncoKB annotation:") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  geom_vline(xintercept = cutoff, size = 0.25, linetype = "dashed", color = "#d6d6d6") +
#  ggpubr::stat_cor(aes(color = min_nt_change, label = paste(..r.label.., ..p.label.., sep = "~`,`~")), label.x.npc = "left", label.y.npc = "top" , size = 2) +
#   geom_smooth(aes(), color = "black", size = 0.5, method = "lm", se = TRUE) +
  xlab("Transforming potential") +
  ylab("Cosmic incidence (Log10 count+1)") +
  geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% label$mutation) %>% 
                    filter(ha1e_wt_lfc > 1 | cosmic_incidence > 1.6) %>% 
                    dplyr::filter(!mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation), color = "black", size = 4, force = 35, min.segment.length = 0.1, segment.size = 0.15) +
    geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation), color = 'black', size = 4, nudge_x = 0.2, nudge_y = 0.1, min.segment.length = 0.2, segment.size = 0.2) +
  theme_bw() +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_y_continuous(limits = c(-0.5, 4.5), breaks = seq(-2, 4, by = 1))
    

plot3 <- data %>%
  ggplot(aes(x = ha1e_wt_lfc, y = cosmic_incidence)) +
       geom_smooth(aes(color = min_nt_change),color = "white", size = 0.5, method = "lm", se = FALSE) +
      geom_hline(yintercept = 0, size = 0.2, linetype = "solid", color = "black") +
      geom_vline(xintercept = 0, size = 0.2, linetype = "solid", color = "black") +
  geom_point(aes(size = annotation), shape = 16,  alpha = 0.3) +
      geom_point(aes(size = annotation, color = min_nt_change), shape = 21,, color= "black") +
  theme(aspect.ratio = 1,
        axis.ticks = element_line(colour = "black", size = 7),
        axis.text.x = element_text(angle = 0, color = "black", size = 14),
        axis.text.y = element_text(angle = 0, color = "black", size = 14)) +
 # scale_color_manual(values = c("SNS" = "red", "DNS" = "navy", "TNS" = "#00630c"), , name = "Minimum nucleotide \nchange:") +
  scale_size_manual(breaks = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    labels = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    values = c(0.75, 0.75, 1.5, 2.5, 4),
                    name = "OncoKB annotation:") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  geom_vline(xintercept = cutoff, size = 0.25, linetype = "dashed", color = "#d6d6d6") +
#  ggpubr::stat_cor(aes(color = min_nt_change, label = paste(..r.label.., ..p.label.., sep = "~`,`~")), label.x.npc = "left", label.y.npc = "top" , size = 2) +
   geom_smooth(aes(), color = "black", size = 0.5, method = "lm", se = FALSE) +
  xlab("Transforming potential") +
  ylab("Cosmic incidence (Log10 count+1)") +
    geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation), color = "black", size = 4, nudge_x = 0.2, nudge_y = 0.1, min.segment.length = 0.2, segment.size = 0.2) +
  theme_bw() +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_y_continuous(limits = c(-0.5, 4.5), breaks = seq(-2, 4, by = 1))
    

plot4 <- data %>%
  ggplot(aes(x = ha1e_wt_lfc, y = cosmic_incidence)) +
     geom_smooth(aes(color = min_nt_change),color = "white", size = 0.5, method = "lm", se = FALSE) +
        geom_hline(yintercept = 0, size = 0.2, linetype = "solid", color = "black") +
      geom_vline(xintercept = 0, size = 0.2, linetype = "solid", color = "black") +
  geom_point(data = . %>% 
                dplyr::filter(!mutation %in% c("G12D", "G12V", "G12L", "G12Q")), aes(size = annotation), shape = 16,  alpha = 0.3) +
    geom_point(data = . %>% 
                dplyr::filter(mutation %in% c("G12D", "G12V", "G12L", "G12Q")), aes(size = annotation, color = min_nt_change), shape = 16,  alpha = 0.3) +
      geom_point(aes(size = annotation, color = min_nt_change), shape = 21,, color= "black") +
  theme(aspect.ratio = 1,
        axis.ticks = element_line(colour = "black", size = 7),
        axis.text.x = element_text(angle = 0, color = "black", size = 14),
        axis.text.y = element_text(angle = 0, color = "black", size = 14)) +

  scale_size_manual(breaks = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    labels = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    values = c(0.75, 0.75, 1.5, 2.5, 4),
                    name = "OncoKB annotation:") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  geom_vline(xintercept = cutoff, size = 0.25, linetype = "dashed", color = "#d6d6d6") +
     scale_color_manual(values = c("SNS" = "red", "DNS" = "navy", "TNS" = "#00630c"), , name = " nucleotide \nchange:") +
# ggpubr::stat_cor(aes(color = min_nt_change, label = paste(..r.label.., ..p.label.., sep = "~`,`~")), label.x.npc = "left", label.y.npc = "top" , size = 2) +
   geom_smooth(aes(), color = "black", size = 0.5, method = "lm", se = FALSE) +
  xlab("Transforming potential") +
  ylab("Cosmic incidence (Log10 count+1)") +
    geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation, color = min_nt_change), size = 4, nudge_x = 0.2, nudge_y = 0.1, min.segment.length = 0.2, segment.size = 0.2)  +
  theme_bw() +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_y_continuous(limits = c(-0.5, 4.5), breaks = seq(-2, 4, by = 1))
    
    

plot5 <- data %>%
  ggplot(aes(x = ha1e_wt_lfc, y = cosmic_incidence)) +
        geom_hline(yintercept = 0, size = 0.2, linetype = "solid", color = "black") +
      geom_vline(xintercept = 0, size = 0.2, linetype = "solid", color = "black") +
  geom_point(aes(size = annotation, color = min_nt_change), shape = 16, alpha = 0.5) +
    geom_point(aes(size = annotation, color = min_nt_change), shape = 21,, color= "black") +
  theme(aspect.ratio = 1,
        axis.ticks = element_line(colour = "black", size = 7),
        axis.text.x = element_text(angle = 0, color = "black", size = 14),
        axis.text.y = element_text(angle = 0, color = "black", size = 14),
        legend.position = "none") +
  scale_color_manual(values = c("SNS" = "red", "DNS" = "navy", "TNS" = "#00630c"), , name = " nucleotide \nchange:") +
  scale_size_manual(breaks = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    labels = c("Unknown", "Inconclusive", "Likely Neutral" , "Likely Oncogenic", "Oncogenic"),
                    values = c(0.75, 0.75, 1.5, 2.5, 4),
                    name = "OncoKB annotation:") +
  guides(fill = guide_legend(override.aes = list(size = 4))) +
  geom_vline(xintercept = cutoff, size = 0.25, linetype = "dashed", color = "#d6d6d6") +
#  ggpubr::stat_cor(aes(color = min_nt_change, label = paste(..r.label.., ..p.label.., sep = "~`,`~")), label.x.npc = "left", label.y.npc = "top" , size = 2) +
   geom_smooth(aes(color = min_nt_change), size = 0.5, method = "lm", se = FALSE) +
  xlab("Transforming potential") +
  ylab("Cosmic incidence (Log10 count+1)") +
    geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% label$mutation) %>% 
                    filter(ha1e_wt_lfc > 1 | cosmic_incidence > 1.6) %>% 
                    dplyr::filter(!mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation, color = min_nt_change), size = 4, force = 35, min.segment.length = 0.05, segment.size = 0.1) +
    geom_text_repel(data = . %>% 
                    dplyr::filter(mutation %in% c("G12D", "G12V", "G12L", "G12Q")), 
                  aes(label = mutation, color = min_nt_change), size = 4, nudge_x = 0.2, nudge_y = 0.1, min.segment.length = 0.2, segment.size = 0.2) +
  theme_bw() +
  scale_x_continuous(breaks = seq(-3, 3, by = 1)) +
  scale_y_continuous(limits = c(-0.5, 4.5), breaks = seq(-2, 4, by = 1))
    

ggsave("plot1.png", plot = plot1, dpi = 600, width = 7, height = 5, units = "in")
ggsave("plot2.png", plot = plot2, dpi = 600,  width = 7, height = 5, units = "in")
ggsave("plot3.png", plot = plot3, dpi = 600,  width = 7, height = 5, units = "in")
ggsave("plot4.png", plot = plot4, dpi = 600,  width = 7, height = 5, units = "in")
ggsave("plot5.png", plot = plot5, dpi = 600, width = 7, height = 5, units = "in")


```

# --- Figure 1D: HA1E KRAS WT DMS screen / Poisson model comparison --- #

```{r}

options(datatable.fread.datatable = FALSE)

sns <- fread("./datasets_publication/figure_1/kras_wt_nucleotide_changes.csv") %>%
  dplyr::mutate(min_nt_change = case_when(n_SNS != 0 ~ "SNS",
                                          n_SNS == 0 & n_DNS != 0 ~ "DNS",
                                          n_SNS == 0 & n_DNS == 0 & n_TNS != 0 ~ "TNS")) %>%
  dplyr::select(mutation, min_nt_change) %>%
  dplyr::filter(min_nt_change == "SNS",
                substr(mutation, 1, 1) != substr(mutation, nchar(mutation), nchar(mutation))) # exclude silent mutations

data <- fread("./datasets_publication/figure_1/cosmic_count_prediction_results_SNS_mut_sig.csv") %>%
  dplyr::mutate(residue = substr(mutation,1,nchar(mutation)-1)) 

fit <- data %>%
  dplyr::mutate(residual = observed - predicted) %>%
  dplyr::group_by(model) %>%
  dplyr::summarise(cor = cor.test(observed, predicted)$estimate,
                   p = cor.test(observed, predicted)$p.value,
                   mae = mean(abs(observed - predicted)),
                   rmse = sqrt(mean((observed - predicted)^2)),
                   r2 = 1 - sum((observed - predicted)^2) / sum((observed - mean(observed))^2))
  
data %<>%
  dplyr::group_by(model, residue) %>%
  dplyr::summarise(observed = sum(observed),
                   predicted = sum(predicted)) %>% 
  dplyr::ungroup() %>%
  tidyr::pivot_longer(cols = c("observed", "predicted"),  names_to = "metric", values_to = "count") %>%
  dplyr::mutate(position = as.numeric(str_extract(residue, "[[:digit:]]+")),
                model = factor(model, levels = c("mutational_signatures", "functional_score", "combined_model")),
                index = paste(model, metric, sep = "_"),
                index = ifelse(index == "combined_model_observed", "observed_Cosmic", index)) %>%
  dplyr::filter(index %in% c("mutational_signatures_predicted","functional_score_predicted", "combined_model_predicted", "observed_Cosmic")) %>%
  dplyr::mutate(index = factor(index, levels = c("mutational_signatures_predicted","functional_score_predicted", "combined_model_predicted", "observed_Cosmic"))) %>% 
  dplyr::select(index, residue, position, count)  %>%
  dplyr::arrange(position)

colors <- c("mutational_signatures_predicted" = "grey50",
            "functional_score_predicted" = "navy",
            "combined_model_predicted" = "firebrick1",
            "observed_Cosmic" = "forestgreen")

data %>%
  dplyr::mutate(count = count + 1) %>%
  ggplot(aes(x = position, y = count)) +
  geom_line(aes(color = index), size = 0, stat = "identity", lwd = 0.25) +
  theme_classic() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        aspect.ratio = 3, 
        strip.text = element_text(size = 5)) +
  ylab("Aggregated SNS mutation count per residue") +
  xlab("KRAS residue") +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  scale_y_continuous(trans = 'log10', labels = function(x) format(x, scientific = FALSE)) + 
  annotation_logticks(sides = "b", outside = FALSE, short = unit(0.05, "cm"),  mid = unit(0.1, "cm"),  long = unit(0.15, "cm")) +
  scale_x_continuous(limits = c(2, 188), breaks = c(2, 50, 100, 150, 188)) +
  geom_text_repel(data = . %>% 
                    dplyr::filter(count >= 100 | residue %in% c("G12", "G13", "Q61", "K117", "A146")),
                  aes(label = residue, color = index),
                  size = 2, 
                  force_pull = 0,
                  force = 10,
                  nudge_x = 0.25,
                  direction = "y",
                  hjust = 0,
                  segment.size = 0.25,
                  min.segment.length = 0) +
  ylab("Total SNS mutation count per residue") +
  xlab("KRAS residue") +
  geom_vline(xintercept = c(12, 13, 61, 117, 146), linetype = "dashed", size = 0.25) +
  coord_flip() +
  guides(color = "none",
         fill = "none") +
  facet_wrap(. ~ index, nrow = 1)

```
